### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by bpmweel** [NLeSC/xenon-flow#21]
I was thinking we should get a nice name for this project.
Since we're calling things by elements at the escience center I did a short survey on some options.

Criteria:

1. Not yet taken by a user or organization on github
2. <name>.github.io not yet taken
3. Sound cool

Options:
- Promethium
- Zirconium
- Tungsten

**Comment by nielsdrost** [comment]
After a short discussion with Berend:

- Agreed xenon-cwl is to "bland"
- Consider to keep Xenon in the name somewhere to show this is closely related to Xenon (and does not make sense without Xenon). Akin to "Docker Swarm" and "Xenon CLI"

Current suggested name: "Xenon Flow".

Though hinting at the purpose, this would also give us some "room" to add things like a java/xenon/slurm based multicore/multinode cwl runner, without needed a new name again ;-)

@jmaassen any thoughts on naming this?

**Comment by bpmweel** [comment]
We have converged outside of github on Xenon Flow, so this change needs to be applied to the various files and github repo's.

**Comment by bpmweel** [comment]
Fixed with f19d5be
