### ISSUE TITLE
Support for python environments

### ISSUE THREAD

**Issue by dafnevk** [NLeSC/xenon-flow#24]
It would be very useful if the remote command can start in a python environment.

Config something like:

```
environment:
       type: conda
       name: adh
```

**Comment by Narasimhamurthygn** [comment]
How to Write a function in Python or Haskell convert a Private key (Ed25519 curve) to 24 word mnemonic, based on the BIP39 standard?

**Comment by mr-c** [comment]
Hello @Narasimhamurthygn , this isn't the place for that sort of question. Cheers,

**Comment by mr-c** [comment]
@dafnevk For that, see https://www.commonwl.org/v1.0/CommandLineTool.html#SoftwareRequirement & how we support it in the CWL reference runner: https://github.com/common-workflow-language/cwltool/#leveraging-softwarerequirements-beta

**Comment by bpmweel** [comment]
@mr-c The problem is not using python environments when cwl runner is running. The cwlrunner itself is usually also installed in a virtualenv, so xenon-flow needs to enable it before invoking cwltool or another runner.

**Comment by bpmweel** [comment]
Since there are many python environments and many ways to start them the best solution seems to internalise the wrapper scripts I used before.

Therefore from now on the cwlCommand should be a bash (or other terminal) script that does the appropriate setup and calls the cwl runner. For instance:

```
cwlCommand: |
            #!/usr/bin/env bash

            source /Users/bweel/miniconda2/bin/activate cwltool && cwltool $@
```
