### ISSUE TITLE
Create MVP Design picture

### ISSUE THREAD

**Issue by nielsdrost** [NLeSC/xenon-flow#7]
Base on this whiteboard picture:

![img_20170511_144635](https://cloud.githubusercontent.com/assets/1703440/25949966/a70686da-3659-11e7-9e6d-462140934ccc.jpg)

**Comment by bpmweel** [comment]
@nielsdrost Does ![this image](https://github.com/NLeSC/xenon-cwl/blob/master/docs/architecture_diagram.png "Architecture Image") show enough, or does it need more information
